const locals = {
    TITULO_PAGINA: "LISTADO DE PROYECTOS",
    CerrarSesion: "Cerrar Sesión",
    CROQUIS:"Croquis",
    PROYECTOS:"Proyecto",
    TRABAJO:"Trabajo",
    Mote:"Mote",
    Promotor:"Promotor",
    Situacion:"Situación",
    Localidad:"Localidad",
    Telefono:"Teléfono",
    Croquis_Inicio:"Croquis",
    Croquis_Fin:"Fin", 
    Proyecto_Ejecucion_Inicio:"Proy.Ejecucion", 
    Proyecto_Ejecucion_Fin:"Fin", 
    Visado_Enviado:"V.Enviado",
    Visado_Descargado:"V.Descargado",
    Licencia:"Licencia",
    Factura:"Factura",
    Obras_Construccion_Inicio:"Obras",
    Obras_Construccion_Fin:"Fin", 
    VisadoFO_Enviado:"VFO.Enviado", 
    VisadoFO_Descargado:"VFO.Descargado", 
    FacturaFO:"FacturaFO", 
    Estado:"Estado",
    Editar:"Editar",
    subheader:{
        CROQUIS:"Croquis",
        Proyecto_Ejecucion: "Proyecto ejecución",
        Visado: "Visado",
        Obras_Construcción: "Obras de construcción",
        VisadoFO: "Visado F.O.",
        Inicio: "Inicio",
        Fin: "Fin",
        Enviado: "Enviado",
        Descargado: "Descargado",
        FacturaFO: "Factura F.O."
    }
}

export default locals;